# Evolved from starter example and setup to debug release builds
# Docs at https://aka.ms/yaml

trigger:
- master

jobs:
  - job: build
    strategy:
      matrix:
        macos_x86:
          imageName: "macOS-11"
          CMAKE_OSX_ARCHITECTURES: "x86_64"
          MACOSX_DEPLOYMENT_TARGET: 10.14
        macos_arm:
          imageName: "macOS-11"
          CMAKE_OSX_ARCHITECTURES: "arm64"
          MACOSX_DEPLOYMENT_TARGET: 11
        linux_x86:
          imageName: "ubuntu-latest"
          CMAKE_OSX_ARCHITECTURES: ""
          MACOSX_DEPLOYMENT_TARGET: ""
    pool:
      vmImage: $(imageName)

    steps:
      - script: echo "Hello, world on $(imageName) $(CMAKE_OSX_ARCHITECTURES)"
        displayName: 'Run a one-line script'

      - bash: |
          brew install pkg-config
        displayName: "Add pkg-config" 
        condition: eq(variables['Agent.OS'], 'Darwin')

      - bash: cmake --version
        displayName: "Check cmake"
