name: artifacts

on:
  #pull_request:
  #  paths-ignore:
  #    - "apis/python/**"
  #    - ".pre-commit-config.yaml"
  push:
    branches: [main, master]
  release:

env:
  TILEDBSOMA_SHA: "dev"
  TILEDBSOMA_BUILD: "${{ github.workspace }}/tiledb_build"
  TILEDBSOMA_SOURCE: "${{ github.workspace }}/libtiledbsoma"
  TILEDBSOMA_INSTALL: "${{ github.workspace }}/.tiledbsoma_dist/$TILEDBSOMA_SHA"
    
jobs:
  build:
    
    strategy:
      matrix:
        #considering https://stackoverflow.com/questions/65035256/how-to-access-matrix-variables-in-github-actions
        #environ: [macos_x86, macos_arm, linux]
        environ: [linux]
        include:
          - environ: 'macos_x86'
            imageName: "macOS-11"
            CMAKE_OSX_ARCHITECTURES: "x86_64"
            MACOSX_DEPLOYMENT_TARGET: 10.14
            ARTIFACT_OS: 'macos'
            ARTIFACT_ARCH: 'x86_64'
          - environ: 'macos_arm'
            imageName: "macOS-11"
            CMAKE_OSX_ARCHITECTURES: "arm64"
            MACOSX_DEPLOYMENT_TARGET: 11 
            ARTIFACT_OS: 'macos'
            ARTIFACT_ARCH: 'arm64'
          - environ: "linux"
            imageName: "ubuntu-latest"
            CMAKE_OSX_ARCHITECTURES: ""
            MACOSX_DEPLOYMENT_TARGET: ""
            ARTIFACT_OS: 'linux'
            ARTIFACT_ARCH: "x86_64"

    runs-on: ${{ matrix.imageName }}

    steps:

          - uses: actions/checkout@v3
 
          - name: 'Echo variables'
            run: |
              echo "Vars are "
              echo "  image   ${{ matrix.imageName }}"
              echo "  osxarch ${{ matrix.CMAKE_OSX_ARCHITECTURES }}"
              echo "  build   ${{ env.TILEDBSOMA_BUILD }}"
              echo "  install ${{ env.TILEDBSOMA_INSTALL }}"

