name: r2u

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  release:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:22.04
    steps:
      - uses: actions/checkout@v3
      - name: SessionInfo
        run: R -q -e 'sessionInfo()'
      - name: System Dependencies
        # this particular package needs cmake and git to build
        run: apt update -qq && apt install --yes --no-install-recommends cmake git
      - name: Package Dependencies
        # this repo has the actual package in a subdirectory hence the cd
        run: cd apis/r && R -q -e 'remotes::install_deps(".", dependencies=TRUE)'
      - name: Build Package
        run: cd apis/r && R CMD build --no-build-vignettes --no-manual .
      - name: Check Package
        run: cd apis/r && R CMD check --no-vignettes --no-manual tiledbsoma_*.tar.gz

        
