## cf https://github.com/marketplace/actions/yet-another-upload-release-asset-action

name: release

on:
  #pull_request:
  #  paths-ignore:
  #    - "apis/python/**"
  #    - ".pre-commit-config.yaml"
  #push:
  #  branches: [main, master]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # steps for building assets
      - run: echo "It is now " $(date) > release_asset.txt

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.PAT }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release_asset.txt 
